### ISSUE TITLE
Add Support for Tag Swapping on Rehype-Stringify

### ISSUE THREAD

**Issue by alexisart** [rehypejs/rehype#130]
### Initial checklist

- [X] I read the [support docs](https://github.com/rehypejs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/rehypejs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/rehypejs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Arehypejs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Problem

rehype-stringify should have a `components` option just like rehype-react.

This problem exists because I want to be able to convert my markdown to the limited set of HTML that Mastodon provides for their posts. I plan on implementing custom classes for formatting html tags in a way that is usable in a Mastodon post.

### Solution

Add support for changing the html tags in rehype-stringify. Using the same format that rehype-react is fine

### Alternatives

Convert to react first, then render results

**Comment by ChristianMurphy** [comment]
Heya @alexisart! 👋 

Some context, `rehype` generally works with the HTML AST (hast).
Elements, properties, and text can be modified with plugins using the tree.
https://unifiedjs.com/learn/ give a good intro to the AST.
https://github.com/syntax-tree/unist-util-visit-parents and https://github.com/jaywcjlove/rehype-rewrite are two utilities that can help with rewriting.

`rehype-react` has a components prop, because React components are different from HTML and cannot be represented in `hast`.
`rehype-stringify` on the other hand works exclusively through `hast`, and as such, the existing utilities can be leveraged to great effect.

**Comment by wooorm** [comment]
Hey! :+1: on Christian’s answer.

Here’s a little plugin that can rewrite just tag names:

```js
/**
 * @typedef {import('hast').Root} Root
 */

import {visit} from 'unist-util-visit'

/** @type {Record<string, string>} */
const components = {
  h1: 'h2'
}

/** @type {import('unified').Plugin<[], Root>} */
export default function rehypeComponents() {
  return function (tree) {
    visit(tree, function (node) {
      if (node.type === 'element' && Object.hasOwn(components, node.tagName)) {
        node.tagName = components[node.tagName]
      }
    })
  }
}
```

Closing as it is intentional to keep the core small and lean, while letting plugins do everything they can, as Christian points out!
