### ISSUE TITLE
Unexpected html codes when parsing attributes with quotes

### ISSUE THREAD

**Issue by benabel** [rehypejs/rehype#34]
### Subject of the issue

The html codes for quotes char on data-attributes are the `js` ones but not the `html` ones.

- `'` -> `&#x27; ` instead of `&#x39; `  maybe because `'` is `\u0027` in `js`.
- `"` -> `&#x22; ` instead of `&#x34; ` maybe because `'` is `\u0022` in `js`.

I created a failing test for this bug on a fresh fork of the repo. https://github.com/benabel/rehype/commit/09f20182aec9c22bb482d5d1112d1b4f728467d6

### Your environment

*   **OS**: linux
*   **Packages**: rehype-stringify
*   **Env**:  yarn

### Steps to reproduce

Stringify this html code, or run test api on the fork: https://github.com/benabel/rehype/commit/09f20182aec9c22bb482d5d1112d1b4f728467d6

```html
<p data-content="This the new example with a 'quotation' mark"></p>
<p data-content='This the new example with a "quotation" mark'></p>
```

### Expected behavior

```html
<p data-content="This the new example with a &#x39;quotation&#x39; mark"></p>
<p data-content="This the new example with a &#x34;quotation&#x34; mark"></p>
```

### Actual behavior

```html
<p data-content="This the new example with a &#x27;quotation&#x27; mark"></p>
<p data-content="This the new example with a &#x22;quotation&#x22; mark"></p>'
```

**Comment by wooorm** [comment]
The current behavior is the correct behavior. Try it out in a browser! Your “expected” example will show digits instead of quotes:

<img width="579" alt="Screen Shot 2020-05-07 at 8 12 38 am" src="https://user-images.githubusercontent.com/944406/81260555-86113900-903a-11ea-8206-4de3337b4684.png">

Whereas the actual behavior gives:

<img width="595" alt="Screen Shot 2020-05-07 at 8 13 07 am" src="https://user-images.githubusercontent.com/944406/81260589-975a4580-903a-11ea-9399-bbe7f5d50cf3.png">

---

HTML has hexadecimal (`&#x27;`), decimal (`&#39;`), and named (`&quot;`) character references: In JS, the hexadecimals are used with the `\u` unicode escape.

**Comment by benabel** [comment]
You're right, I didn't notice the little `x` before the code. Sorry for the noise, thanks for your patience.
